"""
Streamlit frontend for bot detection system
"""
import streamlit as st
import requests
import pandas as pd
from datetime import datetime

# Page configuration
st.set_page_config(
    page_title="Bot Detection System",
    page_icon="🤖",
    layout="wide",
    initial_sidebar_state="expanded"
)

# Backend API endpoint
API_BASE_URL = "http://localhost:8000/api"

st.title("🤖 Bot Detection System")
st.markdown("---")

# Sidebar
with st.sidebar:
    st.header("Configuration")
    
    model_choice = st.selectbox(
        "Select Model",
        ["bert_fox", "roberta_fox", "distilbert_fox", "xlm_roberta_fox"]
    )
    
    st.markdown("---")
    st.subheader("About")
    st.info(
        """
        This application detects whether given text is generated by a bot or written by humans.
        
        **Available Models:**
        - BERT-FoX
        - RoBERTa-FoX
        - DistilBERT-FoX
        - XLM-RoBERTa-FoX
        """
    )

# Main content
col1, col2 = st.columns([2, 1])

with col1:
    st.header("Input Text")
    input_text = st.text_area(
        "Enter text to analyze:",
        height=150,
        placeholder="Paste your text here for bot detection analysis..."
    )

with col2:
    st.header("Options")
    submit_button = st.button(
        "🔍 Analyze",
        use_container_width=True,
        type="primary"
    )

# Process input
if submit_button:
    if not input_text.strip():
        st.error("Please enter some text to analyze.")
    else:
        with st.spinner("Analyzing text..."):
            try:
                # Send request to API
                response = requests.post(
                    f"{API_BASE_URL}/detect/",
                    json={
                        "text": input_text,
                        "model": model_choice
                    },
                    timeout=30
                )
                
                if response.status_code == 200:
                    result = response.json()
                    
                    # Display results
                    st.markdown("---")
                    st.header("Results")
                    
                    col1, col2, col3 = st.columns(3)
                    
                    with col1:
                        st.metric(
                            "Prediction Score",
                            f"{result['prediction']:.4f}",
                            delta=f"{(result['prediction'] * 100):.2f}%"
                        )
                    
                    with col2:
                        is_bot = result['is_bot']
                        st.metric(
                            "Classification",
                            "Bot 🤖" if is_bot else "Human 👤",
                            delta="Likely Bot" if is_bot else "Likely Human"
                        )
                    
                    with col3:
                        st.metric(
                            "Model Used",
                            result['model']
                        )
                    
                    # Display gauge
                    st.markdown("---")
                    
                    # Simple custom gauge chart
                    prediction_value = result['prediction']
                    
                    col_left, col_center, col_right = st.columns([1, 2, 1])
                    with col_center:
                        progress_color = "red" if prediction_value > 0.5 else "green"
                        st.write(f"**Confidence Gauge:**")
                        st.progress(min(prediction_value, 1.0))
                        st.write(f"Human {prediction_value * 100:.1f}% Bot")
                
                else:
                    st.error(f"API Error: {response.status_code}")
                    st.error(response.json().get('error', 'Unknown error'))
            
            except requests.exceptions.ConnectionError:
                st.error(
                    "⚠️ Cannot connect to backend API. "
                    "Make sure Django server is running at http://localhost:8000"
                )
            except Exception as e:
                st.error(f"Error: {str(e)}")

# History section
st.markdown("---")
st.header("Detection History")

try:
    response = requests.get(f"{API_BASE_URL}/results/?limit=10")
    if response.status_code == 200:
        results = response.json()
        
        if isinstance(results, dict):
            results = results.get('results', [])
        
        if results:
            # Convert to DataFrame
            df = pd.DataFrame(results)
            
            # Format display
            display_df = df[['text', 'model_used', 'prediction', 'is_bot', 'created_at']].copy()
            display_df.columns = ['Text', 'Model', 'Score', 'Is Bot', 'Created At']
            display_df['Score'] = display_df['Score'].apply(lambda x: f"{x:.4f}")
            display_df['Is Bot'] = display_df['Is Bot'].apply(lambda x: "Yes 🤖" if x else "No 👤")
            
            st.dataframe(display_df, use_container_width=True)
        else:
            st.info("No detection history yet.")

except:
    st.info("Backend not available. Run the Django server to see history.")

st.markdown("---")
st.caption("Bot Detection System v1.0 | Powered by Django + Streamlit")
